import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Dunkin' Nutrition Labels</title>
      </Head>

      <main>
        <section className='hero'>
          <div className="hero-left">
            <h1 className="header-title">Nutrition Labels Made Easy</h1>
          </div>
          <div className="hero-right">
            <Image className="image-hero" src='/../public/assets/nutrition_label.jpg' alt={'nutrition label example image'} width={350} height={700}/>
          </div>
        </section>
        <section className='item-section'>
          <h2>Select the item category and we will generate the appropriate label:</h2>
          <ul className="menu-items">
            <li>
              <Link href="/nutritionlabel">
              <Image src="/../public/assets/hot_coffee.png" alt='hot coffee image' width={100} height={100}/>
              <p className="item-description">Hot Coffees</p>
              </Link>
            </li>
            <li>
              <Image src="/../public/assets/iced_americano.png" alt='iced coffee image' width={100} height={100}/>
              <p className="item-description">Iced Coffees</p>
            </li>
            <li>
              <Image src="/../public/assets/hot_tea.png" alt='hot tea image' width={100} height={100}/>
              <p className="item-description">Hot Teas</p>
            </li>
            <li>
              <Image src="/../public/assets/iced_tea.png" alt='iced tea image' width={100} height={100}/>
              <p className="item-description">Iced Teas</p>
            </li>
            <li>
              <Image src="/../public/assets/hot_chai_latte.png" alt='hot drinks image' width={100} height={100}/>
              <p className="item-description">Other Hot Drinks</p>
            </li>
            <li>
              <Image src="/../public/assets/iced_matcha_latte.png" alt='iced drinks image' width={100} height={100}/>
              <p className="item-description">Other Iced Drinks</p>
            </li>
            <li>
              <Image src="/../public/assets/frozen_coffee.png" alt='frozen drink image' width={100} height={100}/>
              <p className="item-description">Frozen Drinks</p>
            </li>
            <li className="sandwich">
              <Image src="/../public/assets/SourdoughBNT.png" alt='iced latte image' width={200} height={200}/>
              <p className="item-description">Sandwiches & More</p>
            </li>
          </ul>
        </section>
      </main>
      <footer>
      </footer>
    </>
  )
}
