import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Script from 'next/script';


export default function nutrition_label(){
    return(<>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>NutLab: Nutrition Label</title>
    </Head>

    <main>
        <section className='options'>
            <form>

                <fieldset className='size-options'>
                    <legend>Size</legend>
                    <label className="size">
                        <input id="Small" type="radio" name="size" className="size" value="Small" tabIndex={0}/>
                        <p>S</p>
                    </label>
                    <label className="size">
                        <input id="Medium" type="radio" name="size" className="size" value="Medium" tabIndex={0}/>
                        <p>M</p>
                    </label>
                    <label className="size">
                        <input id="Large" type="radio" name="size" className="size" value="Large" tabIndex={0}/>
                        <p>L</p>
                    </label>
                </fieldset>


                <fieldset className='drink-options'>
                    <legend>Drink Type</legend>
                    <div className='drink-type dropdown'>
                        <div className='select' id="variety" aria-hidden="true">
                            <span className='selected'>Hot Coffees</span>
                            <div className="caret"></div>
                        </div>
                        <ul className='menu'>
                            <li className="active" value="hot-coffees">Hot Coffees</li>
                            <li value="iced-coffees">Iced Coffees</li>
                            <li value="hot-teas">Hot Teas</li>
                            <li value="iced-teas">Iced Teas</li>
                            <li value="other-hot">Other Hot Drinks</li>
                            <li value="other-iced">Other Iced Drinks</li>
                            <li value="frozen">Frozen Drinks</li>
                        </ul>
                    </div>
                </fieldset>

                <fieldset className='drink-name-options'>
                    <legend>Drink Name</legend>
                    <div className='drink-name dropdown iced-coffee'>
                        <div className='select' id="name" aria-hidden="true">
                            <span className='selected'>Iced Coffee</span>
                            <div className="caret"></div>
                        </div>
                        <ul className='menu'>
                            <li className="active" value="iced-coffee">Iced Coffee</li>
                            <li value="coldbrew">Coldbrew</li>
                            <li value="iced-americano">Iced Americano</li>
                            <li value="iced-lattee">Iced Latte</li>
                            <li value="iced-signature-latte">Iced Signature Latte</li>
                            <li value="iced-macchiato">Iced Macchiato</li>
                            <li value="iced-cappuccino">Iced Cappuccino</li>
                        </ul>
                    </div>
                </fieldset>

                <fieldset className='dairy-name-options'>
                    <legend>Dairy</legend>
                    <div className='dairy dropdown iced-coffee'>
                        <div className='select' id="dairy" aria-hidden="true">
                            <span className='selected'>Whole Milk</span>
                            <div className="caret"></div>
                        </div>
                        <ul className='menu'>
                            <li className="active" value="wholemilk">Whole Milk</li>
                            <li value="skimmilk">Skim Milk</li>
                            <li value="oatmilk">Oatmilk</li>
                            <li value="coconutmilk">Coconutmilk</li>                     
                        </ul>
                    </div>
                </fieldset>

                <fieldset className='sweetener-options'>
                    <legend>Sweetener</legend>
                    <div className='sweetener dropdown'>
                        <div className='select' id="sweetener" aria-hidden="true">
                            <span className='selected'>Sugar</span>
                            <div className="caret"></div>
                        </div>
                        <ul className='menu'>
                            <li value="none">None</li>
                            <li className="active" value="sugar">Sugar</li>
                            <li value="cane-sugar">Liquid Cane Sugar</li>
                            <li value="equal">Equal</li>
                            <li value="splenda">Splenda</li>
                            <li value="sweet-n-low">Sweet'N Low</li>
                            <li value="stevia">Stevia in the Raw</li>
                        </ul>
                    </div>
                </fieldset>

                <fieldset className='add-on-options'>
                    <legend>Add Ons</legend>
                    <label className="espresso-shot">
                        <input type="checkbox" name="addon" className="addon" value="espresso-shot"/>
                        <span className="checkmark"></span><p>Espresso Shot</p>
                    </label>
                    <label className="cold-foam">
                        <input type="checkbox" name="addon" className="addon" value="cold-foam"/>
                        <span className="checkmark"></span><p>Cold Foam</p>
                    </label>
                    <label className="whipped-cream">
                        <input type="checkbox" name="addon" className="addon" value="whipped-cream"/>
                        <span className="checkmark"></span><p>Whipped Cream</p>
                    </label>
                </fieldset>


            </form>
        </section>
    </main>
    <Script src="/scripts/select.js" strategy='lazyOnload' />
    </>);
}
